<a href="https://colab.research.google.com/github/Alok594/alok/blob/main/Tutorial_9_Python_Pandas_Tutorials_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Tutorial 9- Python Pandas Tutorials- Part 1

In Part we are going to learn about
1. Pandas Dataframe
2. Pandas Series
3. Pandas Basic Operations

In [ ]:
!pip install pandas

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
## Create Dataframe-> it is a type of data which is made by using pandas library
# dataframe is nothing but information in table form
# dataframe(data,index,column)<-this is syntex of data
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=["Row1",
                                                      "Row2","Row3",
                                                      "Row4","Row5"],columns=["Column1",
                                                                             "Column2",
                                                                             "Column3",
                                                                             "Column4"])

In [ ]:
# is function mei agr ham kuchh n dale to upar  ka top 5 data dega and  value push kare like 7,8 like that then it will give utne data
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [ ]:
# is function mei agr ham kuchh n dale to last  ka top 5 data dega and  value push kare like 7,8 like that then it will give utne data
df.tail()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
#it will give info about column like type kya hai iska
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  5 non-null      int32
 1   Column2  5 non-null      int32
 2   Column3  5 non-null      int32
 3   Column4  5 non-null      int32
dtypes: int32(4)
memory usage: 120.0+ bytes


In [ ]:
# ye bas wahi column select krega jisme int ya float type data ho and give mean std min info iss tarah ka
df.describe()

Column1    Column2    Column3    Column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [ ]:
##Indexing done by three ways that are given below where loc mean location and iloc mean index location
## columnname,rowindex[loc],rowindex columnindex number[.iloc]
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [ ]:
##columnname
# here we use single nested list becoz yaha ek hi column hai
# differnce between dataframe nad series is that in series there will be either one column or one row and in column there will me more than one row and column and if thow row aor two column are there then they will also be considered as dataframe
type(df['Column1'])

pandas.core.series.Series

In [ ]:
# jab bhi we have to find  more than one  column details we always used multiple nested loop
df[['Column1','Column2','Column3']]

Column1  Column2  Column3
Row1        0        1        2
Row2        4        5        6
Row3        8        9       10
Row4       12       13       14
Row5       16       17       18

In [ ]:
##using row index name loc
df.loc[['Row3','Row4']]

Column1  Column2  Column3  Column4
Row3        8        9       10       11
Row4       12       13       14       15

In [ ]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [ ]:
# in iloc function we give indexing of row and column
# row and column indexing in dataframe also start with 0
df.iloc[2:4,0:2]

Column1  Column2
Row3        8        9
Row4       12       13

In [ ]:
df.iloc[2:,1:]

Column2  Column3  Column4
Row3        9       10       11
Row4       13       14       15
Row5       17       18       19

In [ ]:
##convert dataframe into arrays
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [ ]:
## Basic operations
# niche jo operation hai wo batayega ki koi nan hai ya nhi if kisi colum mein hoga then jtna hoga utna number dikha dega otherwise 0
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [ ]:
# nan means not a number
df=pd.DataFrame(data=[[1,np.nan,2],[1,3,4]],index=["Row1",
                                                      "Row2"],columns=["Column1",
                                                                             "Column2",
                                                                             "Column3",
                                                                             ])

In [ ]:
df

Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4

In [ ]:
df.isnull().sum()

Column1    0
Column2    1
Column3    0
dtype: int64

In [ ]:
df.isnull().sum()==0

Column1     True
Column2    False
Column3     True
dtype: bool

In [ ]:
df

In [ ]:
# tell me about ki koi number kitni bar aya hai
df['Column3'].value_counts()

2    1
4    1
Name: Column3, dtype: int64

In [ ]:
df

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [ ]:
# unique function tell me about kis kitne unique number hai
df['Column2'].unique()

array([ 1,  5,  9, 13, 17])

In [ ]:
# ki kitne greater than 2 hai
df[df['Column2']>2]

Column1  Column2  Column3  Column4
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19